spring:
  application:
    name: REST-API
  datasource:
    username:
    password:
    url:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true